import socket
from termcolor import colored
import time
import re

# for the Python-side passing of commands
#HOST = "127.0.0.1"  # The server's hostname or IP address
HOST = socket.gethostname() # or just use (host == '')
PORT = 65432  # The port used by the server

# Flags for different modes of operation
talkToCommsServer = True
listenToCommsServer = True
talkToArduino = False
listenToArduino = False

# Help info printed to screen
def help_info():
    print('\n')
    print(colored('List of commands in opta-comms-client.py', 'magenta'))
    print(colored('help\t', 'yellow'),colored('- prints this information','white'))
    print(colored('stop\t', 'yellow'),colored('- terminates the client and server','white'))
    print(colored('quit\t', 'yellow'),colored('- terminates the client but not the server','white'))
    print(colored('arduino\t', 'yellow'),colored('- prints information about Arduino Opta PLC','white'))
    print('\n')
    
def arduino_info():
    '''
    To access this
    - pip install opcua-client
    - find client in environment (see header above)
    - run opcua-client.exe
    - Navigate: Root>Objects>Real time data>...
    - Check NodeId values as unsigned integers
    - These are nodeId values for Client commands
    
    Existing setup - assembled from left to right
    1) Arduino Opta Wifi
    2) Expansion 0: Digital (Solid State)
    3) Expansion 1: Analog
    '''
    response = input(colored('   Enter "1" for all NodeId info or "2" for I/O info only: ','cyan'))
    if response == '1':
        print('\n')
        print(colored('List of NodeId for Arduino Opta PLC', 'magenta'))
        print(colored('i \t\t - label (type)', 'magenta'))
        print(colored('84\t\t', 'yellow'),colored('- 0:Root','white'))
        print(colored('85\t\t', 'yellow'),colored('- 0:Objects','white'))
        print(colored('2253\t', 'yellow'),colored('- 0:Server','white'))
        print(colored('2254\t', 'yellow'),colored('- 0:ServerArray (string)','white'))
        print(colored('2255\t', 'yellow'),colored('- 0:NamespaceArray (string)','white'))
        print(colored('2256\t', 'yellow'),colored('- 0:ServerStatus (ExtensionObject)','white'))
        print(colored('2257\t', 'yellow'),colored('- 0:StartTime (DateTime)','white'))
        print(colored('2258\t', 'yellow'),colored('- 0:CurrentTime (DateTime)','white'))
        print(colored('2259\t', 'yellow'),colored('- 0:State (Int32)','white'))
        print(colored('2260\t', 'yellow'),colored('- 0:BuildInfo (ExtensionObject)','white'))
        print(colored('2261\t', 'yellow'),colored('- 0:ProductName (String)','white'))
        print(colored('2262\t', 'yellow'),colored('- 0:ProductUri (String)','white'))
        print(colored('2263\t', 'yellow'),colored('- 0:ManufacturerName (String)','white'))
        print(colored('2264\t', 'yellow'),colored('- 0:SoftwareVersion (String)','white'))
        print(colored('2265\t', 'yellow'),colored('- 0:BuildNumber (String)','white'))
        print(colored('2266\t', 'yellow'),colored('- 0:BuildDate (DateTime)','white'))
        print(colored('50129\t', 'yellow'),colored('- 1:AnaExp_1','white'))
        print(colored('50133\t', 'yellow'),colored('- 1:AnalogInputs','white'))
        print(colored('50137\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I1','white'))
        print(colored('50138\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I2','white'))
        print(colored('50139\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I3','white'))
        print(colored('50140\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I4','white'))
        print(colored('50141\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I5','white'))
        print(colored('50142\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I6','white'))    
        print(colored('50134\t', 'yellow'),colored('- 1:AnalogOuputs','white'))    
        print(colored('50143\t', 'yellow'),colored('- 1:Value (Float) - Analog Output O1','white'))    
        print(colored('50144\t', 'yellow'),colored('- 1:Value (Float) - Analog Output O2','white'))    
        print(colored('50136\t', 'yellow'),colored('- 1:LEDs','white'))    
        print(colored('50157\t', 'yellow'),colored('- 1:Value (Boolean) - LED1','white'))    
        print(colored('50158\t', 'yellow'),colored('- 1:Value (Boolean) - LED2','white'))    
        print(colored('50159\t', 'yellow'),colored('- 1:Value (Boolean) - LED3','white'))    
        print(colored('50160\t', 'yellow'),colored('- 1:Value (Boolean) - LED4','white'))    
        print(colored('50161\t', 'yellow'),colored('- 1:Value (Boolean) - LED5','white'))    
        print(colored('50162\t', 'yellow'),colored('- 1:Value (Boolean) - LED6','white'))    
        print(colored('50163\t', 'yellow'),colored('- 1:Value (Boolean) - LED7','white'))    
        print(colored('50164\t', 'yellow'),colored('- 1:Value (Boolean) - LED8','white'))    
        print(colored('50130\t', 'yellow'),colored('- 1:ManufacturerName (String)','white'))    
        print(colored('50131\t', 'yellow'),colored('- 1:ModelName (String)','white'))    
        print(colored('50135\t', 'yellow'),colored('- 1:PwmOutputs','white'))    
        print(colored('50135\t', 'yellow'),colored('- 1:PwmOutputs','white'))    
        print(colored('50145\t', 'yellow'),colored('- 1:PWM1','white'))    
        print(colored('50146\t', 'yellow'),colored('- 1:pwm_period_us (UInt32) - PWM1 period / us','white'))    
        print(colored('50147\t', 'yellow'),colored('- 1:pwm_pulse_width_us (UInt32) - PWM1 pulse width / us','white'))    
        print(colored('50148\t', 'yellow'),colored('- 1:PWM2','white'))    
        print(colored('50149\t', 'yellow'),colored('- 1:pwm_period_us (UInt32) - PWM2 period / us','white'))    
        print(colored('50150\t', 'yellow'),colored('- 1:pwm_pulse_width_us (UInt32) - PWM2 pulse width / us','white'))  
        print(colored('50151\t', 'yellow'),colored('- 1:PWM3','white'))    
        print(colored('50152\t', 'yellow'),colored('- 1:pwm_period_us (UInt32) - PWM3 period / us','white'))    
        print(colored('50153\t', 'yellow'),colored('- 1:pwm_pulse_width_us (UInt32) - PWM3 pulse width / us','white'))  
        print(colored('50154\t', 'yellow'),colored('- 1:PWM4','white'))    
        print(colored('50155\t', 'yellow'),colored('- 1:pwm_period_us (UInt32) - PWM4 period / us','white'))    
        print(colored('50156\t', 'yellow'),colored('- 1:pwm_pulse_width_us (UInt32) - PWM4 pulse width / us','white'))  
        print(colored('50132\t', 'yellow'),colored('- 1:Status (Boolean)','white'))  
        print(colored('50082\t', 'yellow'),colored('- 1:DigExpSoli_0','white'))
        print(colored('50086\t', 'yellow'),colored('- 1:AnalogInputs','white'))
        print(colored('50089\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I1','white'))
        print(colored('50091\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I2','white'))
        print(colored('50093\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I3','white'))
        print(colored('50095\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I4','white'))
        print(colored('50097\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I5','white'))
        print(colored('50252\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I6','white'))
        print(colored('50101\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I7','white'))
        print(colored('50103\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I8','white'))
        print(colored('50105\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I9','white'))
        print(colored('50107\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I10','white'))
        print(colored('50109\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I11','white'))
        print(colored('50111\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I12','white'))
        print(colored('50113\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I13','white'))
        print(colored('50115\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I14','white'))
        print(colored('50117\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I15','white'))
        print(colored('50119\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I16','white'))
        print(colored('50087\t', 'yellow'),colored('- 1:DigitalInputs','white'))
        print(colored('50090\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I1','white'))
        print(colored('50092\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I2','white'))
        print(colored('50094\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I3','white'))
        print(colored('50096\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I4','white'))
        print(colored('50097\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I5','white'))
        print(colored('50100\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I6','white'))
        print(colored('50102\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I7','white'))
        print(colored('50104\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I8','white'))
        print(colored('50106\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I9','white'))
        print(colored('50108\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I10','white'))
        print(colored('50110\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I11','white'))
        print(colored('50112\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I12','white'))
        print(colored('50114\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I13','white'))
        print(colored('50116\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I14','white'))
        print(colored('50118\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I15','white'))
        print(colored('50120\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I16','white'))
        print(colored('50083\t', 'yellow'),colored('- 1:ManufacturerName (String)','white'))
        print(colored('50084\t', 'yellow'),colored('- 1:ModelName (String)','white'))
        print(colored('50088\t', 'yellow'),colored('- 1:Relays','white'))
        print(colored('50121\t', 'yellow'),colored('- 1:Value (Boolean) - Relay 1','white'))
        print(colored('50122\t', 'yellow'),colored('- 1:Value (Boolean) - Relay 2','white'))
        print(colored('50123\t', 'yellow'),colored('- 1:Value (Boolean) - Relay 3','white'))
        print(colored('50124\t', 'yellow'),colored('- 1:Value (Boolean) - Relay 4','white'))
        print(colored('50125\t', 'yellow'),colored('- 1:Value (Boolean) - Relay 5','white'))
        print(colored('50126\t', 'yellow'),colored('- 1:Value (Boolean) - Relay 6','white'))
        print(colored('50127\t', 'yellow'),colored('- 1:Value (Boolean) - Relay 7','white'))
        print(colored('50004\t', 'yellow'),colored('- 1:Value (Boolean) - Relay 8','white'))
        print(colored('50085\t', 'yellow'),colored('- 1:Status (Boolean)','white'))
        print(colored('50128\t', 'yellow'),colored('- 1:Opta','white'))
        print(colored('50057\t', 'yellow'),colored('- 1:AnalogInputs','white'))
        print(colored('50061\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I1','white'))
        print(colored('50061\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I2','white'))
        print(colored('50063\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I3','white'))
        print(colored('50064\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I4','white'))
        print(colored('50065\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I5','white'))
        print(colored('50066\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I6','white'))
        print(colored('50067\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I7','white'))
        print(colored('50068\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I8','white'))
        print(colored('50058\t', 'yellow'),colored('- 1:DigitalInputs','white'))
        print(colored('50069\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I1','white'))
        print(colored('50070\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I2','white'))
        print(colored('50071\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I3','white'))
        print(colored('50072\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I4','white'))
        print(colored('50073\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I5','white'))
        print(colored('50074\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I6','white'))
        print(colored('50075\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I7','white'))
        print(colored('50076\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I8','white'))
        print(colored('50060\t', 'yellow'),colored('- 1:LEDs','white'))
        print(colored('50081\t', 'yellow'),colored('- 1:Value (Boolean) - User LED','white'))
        print(colored('50052\t', 'yellow'),colored('- 1:ManufacturerName (String)','white'))
        print(colored('50053\t', 'yellow'),colored('- 1:ModelName (String)','white'))
        print(colored('50059\t', 'yellow'),colored('- 1:Relays','white'))
        print(colored('50077\t', 'yellow'),colored('- 1:Value (Boolean) - Relay 1','white'))
        print(colored('50078\t', 'yellow'),colored('- 1:Value (Boolean) - Relay 2','white'))
        print(colored('50079\t', 'yellow'),colored('- 1:Value (Boolean) - Relay 3','white'))
        print(colored('50080\t', 'yellow'),colored('- 1:Value (Boolean) - Relay 4','white'))
        print(colored('50054\t', 'yellow'),colored('- 1:Status (Boolean)','white'))
        print(colored('50055\t', 'yellow'),colored('- 1:UserButton','white'))
        print(colored('86\t\t', 'yellow'),colored('- 0:Types','white'))
        print(colored('87\t\t', 'yellow'),colored('- 0: Views','white'))
        print('\n') 
    elif response == '2':
        print('\n')
        print(colored('List of NodeId for Arduino Opta PLC', 'magenta'))
        print(colored('i \t\t - label (type)', 'magenta'))
        print(colored('\tAnalog Expansion (module #3)', 'yellow'))
        print(colored('50137\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I1','white'))
        print(colored('50138\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I2','white'))
        print(colored('50139\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I3','white'))
        print(colored('50140\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I4','white'))
        print(colored('50141\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I5','white'))
        print(colored('50142\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I6','white'))
        print(colored('50143\t', 'yellow'),colored('- 1:Value (Float) - Analog Output O1','white'))    
        print(colored('50144\t', 'yellow'),colored('- 1:Value (Float) - Analog Output O2','white'))    
        print(colored('50157\t', 'yellow'),colored('- 1:Value (Boolean) - LED1','white'))    
        print(colored('50158\t', 'yellow'),colored('- 1:Value (Boolean) - LED2','white'))    
        print(colored('50159\t', 'yellow'),colored('- 1:Value (Boolean) - LED3','white'))    
        print(colored('50160\t', 'yellow'),colored('- 1:Value (Boolean) - LED4','white'))    
        print(colored('50161\t', 'yellow'),colored('- 1:Value (Boolean) - LED5','white'))    
        print(colored('50162\t', 'yellow'),colored('- 1:Value (Boolean) - LED6','white'))    
        print(colored('50163\t', 'yellow'),colored('- 1:Value (Boolean) - LED7','white'))    
        print(colored('50164\t', 'yellow'),colored('- 1:Value (Boolean) - LED8','white'))   
        print(colored('50146\t', 'yellow'),colored('- 1:pwm_period_us (UInt32) - PWM1 period / us','white'))    
        print(colored('50147\t', 'yellow'),colored('- 1:pwm_pulse_width_us (UInt32) - PWM1 pulse width / us','white'))     
        print(colored('50149\t', 'yellow'),colored('- 1:pwm_period_us (UInt32) - PWM2 period / us','white'))    
        print(colored('50150\t', 'yellow'),colored('- 1:pwm_pulse_width_us (UInt32) - PWM2 pulse width / us','white'))    
        print(colored('50152\t', 'yellow'),colored('- 1:pwm_period_us (UInt32) - PWM3 period / us','white'))    
        print(colored('50153\t', 'yellow'),colored('- 1:pwm_pulse_width_us (UInt32) - PWM3 pulse width / us','white'))     
        print(colored('50155\t', 'yellow'),colored('- 1:pwm_period_us (UInt32) - PWM4 period / us','white'))    
        print(colored('50156\t', 'yellow'),colored('- 1:pwm_pulse_width_us (UInt32) - PWM4 pulse width / us','white'))  
        print(colored('\tDigital Solid State Expansion (module #2)', 'yellow'))
        print(colored('50089\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I1','white'))
        print(colored('50091\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I2','white'))
        print(colored('50093\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I3','white'))
        print(colored('50095\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I4','white'))
        print(colored('50097\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I5','white'))
        print(colored('50252\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I6','white'))
        print(colored('50101\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I7','white'))
        print(colored('50103\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I8','white'))
        print(colored('50105\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I9','white'))
        print(colored('50107\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I10','white'))
        print(colored('50109\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I11','white'))
        print(colored('50111\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I12','white'))
        print(colored('50113\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I13','white'))
        print(colored('50115\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I14','white'))
        print(colored('50117\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I15','white'))
        print(colored('50119\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I16','white'))
        print(colored('50090\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I1','white'))
        print(colored('50092\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I2','white'))
        print(colored('50094\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I3','white'))
        print(colored('50096\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I4','white'))
        print(colored('50097\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I5','white'))
        print(colored('50100\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I6','white'))
        print(colored('50102\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I7','white'))
        print(colored('50104\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I8','white'))
        print(colored('50106\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I9','white'))
        print(colored('50108\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I10','white'))
        print(colored('50110\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I11','white'))
        print(colored('50112\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I12','white'))
        print(colored('50114\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I13','white'))
        print(colored('50116\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I14','white'))
        print(colored('50118\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I15','white'))
        print(colored('50120\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I16','white'))
        print(colored('50121\t', 'yellow'),colored('- 1:Value (Boolean) - Relay 1','white'))
        print(colored('50122\t', 'yellow'),colored('- 1:Value (Boolean) - Relay 2','white'))
        print(colored('50123\t', 'yellow'),colored('- 1:Value (Boolean) - Relay 3','white'))
        print(colored('50124\t', 'yellow'),colored('- 1:Value (Boolean) - Relay 4','white'))
        print(colored('50125\t', 'yellow'),colored('- 1:Value (Boolean) - Relay 5','white'))
        print(colored('50126\t', 'yellow'),colored('- 1:Value (Boolean) - Relay 6','white'))
        print(colored('50127\t', 'yellow'),colored('- 1:Value (Boolean) - Relay 7','white'))
        print(colored('50004\t', 'yellow'),colored('- 1:Value (Boolean) - Relay 8','white'))
        print(colored('\tArduino Opta Wifi PLC (module #1)', 'yellow'))
        print(colored('50061\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I1','white'))
        print(colored('50061\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I2','white'))
        print(colored('50063\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I3','white'))
        print(colored('50064\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I4','white'))
        print(colored('50065\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I5','white'))
        print(colored('50066\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I6','white'))
        print(colored('50067\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I7','white'))
        print(colored('50068\t', 'yellow'),colored('- 1:Value (Float) - Analog Input I8','white'))
        print(colored('50069\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I1','white'))
        print(colored('50070\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I2','white'))
        print(colored('50071\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I3','white'))
        print(colored('50072\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I4','white'))
        print(colored('50073\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I5','white'))
        print(colored('50074\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I6','white'))
        print(colored('50075\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I7','white'))
        print(colored('50076\t', 'yellow'),colored('- 1:Value (Boolean) - Digital Input I8','white'))
        print(colored('50081\t', 'yellow'),colored('- 1:Value (Boolean) - User LED','white'))
        print(colored('50077\t', 'yellow'),colored('- 1:Value (Boolean) - Relay 1','white'))
        print(colored('50078\t', 'yellow'),colored('- 1:Value (Boolean) - Relay 2','white'))
        print(colored('50079\t', 'yellow'),colored('- 1:Value (Boolean) - Relay 3','white'))
        print(colored('50080\t', 'yellow'),colored('- 1:Value (Boolean) - Relay 4','white'))
        print(colored('50056\t', 'yellow'),colored('- 1:Value (Boolean) - User Button','white'))
        print('\n')   
    else: 
        print(colored('Please enter "1" or "2" next time', 'magenta'))
 
    
# Interpreter for user string input to client
def send_string_interpreter(sendString,talkToCommsServer,talkToArduino):
    if re.search("help", sendString, re.IGNORECASE):
        help_info()
    if re.search("arduino", sendString, re.IGNORECASE):
        arduino_info()
    if re.search("stop", sendString, re.IGNORECASE):
        print(colored('>: CLIENT AND SERVER SESSION TERMINATED', 'red'))
        talkToCommsServer = False   # close comms with server    
    if re.search("quit", sendString, re.IGNORECASE):
        print(colored('>: CLIENT SESSION ENDED', 'red'))
        talkToCommsServer = False   # close comms with server
    return talkToCommsServer,talkToArduino



# Talking to Comms Server
while talkToCommsServer:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.connect((HOST, PORT))
        #s.sendall(b"Hello, world")
        sendString = input(colored('Input command: ','cyan'))
        talkToCommsServer,talkToArduino = send_string_interpreter(sendString,talkToCommsServer,talkToArduino)
        sendBytes = sendString.encode() # String to bytes
        s.sendall(sendBytes)
        data = s.recv(1024)
        readString = data.decode()      # Bytes to string
        print('   Echo: ' + readString)
        #s.close()
        time.sleep(1)

print(colored('>: Client successfully finished', 'red'))